<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SeguimientosSeeder extends Seeder
{
    public function run(): void
    {
        // Marcas reales en la BD: 71, 72, 73, 74
        // Cliente real: RYM SOLUCIONES EN COMUNICACIONES

        $seguimientos = [
            [
                'marca_id'        => 71,
                'cliente'         => 'RYM SOLUCIONES EN COMUNICACIONES',
                'linea_primaria'  => 'HUAWEI INVERSORES',
                'fecha_apertura'  => '2025-10-01',
                'fecha_cierre'    => '2026-01-17',
                'fecha_facturacion' => '2026-01-20',
                'valor'           => 289733.00,
                'estado_negocio'  => 'Cerrado ganado',
                'estado'          => 'facturado',
                'incoterm'        => 'CIF',
                'anticipos'       => 'Anticipo 30% recibido el 2025-11-15',
                'tiempos_entrega' => '90 días desde confirmación de OC',
                'forma_pago'      => '30% anticipo, 70% contra entrega en puerto',
                'facturacion'     => 'Factura #FV-2026-001 emitida el 2026-01-20',
                'actas_cierre'    => 'Acta de entrega firmada el 2026-01-18',
                'observaciones'   => 'Entrega en Calle 81 #110-34, Bogotá. Sin novedad.',
                'crm_sync_at'     => Carbon::parse('2026-01-17 01:04:01'),
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'marca_id'        => 72,
                'cliente'         => 'RYM SOLUCIONES EN COMUNICACIONES',
                'linea_primaria'  => 'TP_LINK CONECTIVIDAD',
                'fecha_apertura'  => '2026-03-01',
                'fecha_cierre'    => null,
                'fecha_facturacion' => null,
                'valor'           => 50000.00,
                'estado_negocio'  => 'En negociación',
                'estado'          => 'en_proceso',
                'incoterm'        => 'CIF',
                'anticipos'       => 'Anticipo 20% pendiente de recibir',
                'tiempos_entrega' => '60 días desde pago de anticipo',
                'forma_pago'      => '20% anticipo, 80% crédito a 60 días desde entrega en puerto',
                'facturacion'     => null,
                'actas_cierre'    => null,
                'observaciones'   => 'Stock 5 AMARA DDP Funza. En espera de aprobación interna.',
                'crm_sync_at'     => null,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'marca_id'        => 73,
                'cliente'         => 'RYM SOLUCIONES EN COMUNICACIONES',
                'linea_primaria'  => 'TP_LINK CONECTIVIDAD',
                'fecha_apertura'  => '2026-03-15',
                'fecha_cierre'    => null,
                'fecha_facturacion' => null,
                'valor'           => 50000.00,
                'estado_negocio'  => 'Propuesta enviada',
                'estado'          => 'pendiente',
                'incoterm'        => 'DDP',
                'anticipos'       => null,
                'tiempos_entrega' => '45 días',
                'forma_pago'      => '20% anticipo, 80% crédito a 60 días',
                'facturacion'     => null,
                'actas_cierre'    => null,
                'observaciones'   => 'Pendiente respuesta del cliente sobre condiciones financieras.',
                'crm_sync_at'     => null,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'marca_id'        => 74,
                'cliente'         => 'RYM SOLUCIONES EN COMUNICACIONES',
                'linea_primaria'  => 'TP_LINK CONECTIVIDAD',
                'fecha_apertura'  => '2026-02-10',
                'fecha_cierre'    => '2026-04-29',
                'fecha_facturacion' => null,
                'valor'           => 123456.00,
                'estado_negocio'  => 'Cerrado perdido',
                'estado'          => 'declinado',
                'incoterm'        => 'FOB',
                'anticipos'       => null,
                'tiempos_entrega' => null,
                'forma_pago'      => 'Prueba',
                'facturacion'     => null,
                'actas_cierre'    => null,
                'observaciones'   => 'Cliente declinó por precio. Competidor ofreció mejor condición.',
                'crm_sync_at'     => null,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'marca_id'        => 71,
                'cliente'         => 'RYM SOLUCIONES EN COMUNICACIONES',
                'linea_primaria'  => 'HUAWEI INVERSORES',
                'fecha_apertura'  => '2025-08-01',
                'fecha_cierre'    => '2025-12-20',
                'fecha_facturacion' => '2025-12-22',
                'valor'           => 175000.00,
                'estado_negocio'  => 'Cerrado ganado y pagado',
                'estado'          => 'facturado_y_pagado',
                'incoterm'        => 'CIF',
                'anticipos'       => 'Anticipo 30% recibido. Saldo 70% recibido el 2026-02-28.',
                'tiempos_entrega' => '90 días',
                'forma_pago'      => '30% anticipo, 70% a 60 días desde entrega',
                'facturacion'     => 'Factura #FV-2025-089 emitida el 2025-12-22. Pagada el 2026-02-28.',
                'actas_cierre'    => 'Acta firmada 2025-12-21. Sin observaciones.',
                'observaciones'   => 'Negocio completado. Cliente satisfecho.',
                'crm_sync_at'     => Carbon::parse('2026-01-17 01:04:01'),
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'marca_id'        => 72,
                'cliente'         => 'RYM SOLUCIONES EN COMUNICACIONES',
                'linea_primaria'  => 'TP_LINK CONECTIVIDAD',
                'fecha_apertura'  => '2026-01-05',
                'fecha_cierre'    => '2026-02-15',
                'fecha_facturacion' => null,
                'valor'           => 30000.00,
                'estado_negocio'  => 'Cancelado por cliente',
                'estado'          => 'anulado',
                'incoterm'        => 'EXW',
                'anticipos'       => null,
                'tiempos_entrega' => null,
                'forma_pago'      => 'Contado',
                'facturacion'     => null,
                'actas_cierre'    => null,
                'observaciones'   => 'Anulado a solicitud del cliente antes de firma de contrato.',
                'crm_sync_at'     => null,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'marca_id'        => 73,
                'cliente'         => 'RYM SOLUCIONES EN COMUNICACIONES',
                'linea_primaria'  => 'TP_LINK CONECTIVIDAD',
                'fecha_apertura'  => '2026-04-01',
                'fecha_cierre'    => null,
                'fecha_facturacion' => null,
                'valor'           => 48000.00,
                'estado_negocio'  => 'Renovación anual',
                'estado'          => 'recurrencia',
                'incoterm'        => 'CIF',
                'anticipos'       => 'Mismas condiciones del contrato anterior.',
                'tiempos_entrega' => '30 días',
                'forma_pago'      => '50% anticipo, 50% contra entrega',
                'facturacion'     => null,
                'actas_cierre'    => null,
                'observaciones'   => 'Cliente recurrente. Condiciones del contrato anterior aplican.',
                'crm_sync_at'     => null,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
        ];

        DB::table('seguimientos')->insert($seguimientos);

        $this->command->info(' Seguimientos seeder ejecutado: ' . count($seguimientos) . ' registros insertados.');
    }
}